
# Site settings
title: Dan Klammer
email: me@danklammer.com
description: Web Designer & Developer from Cleveland, Ohio
tagline: Pushing to create good design, simple apps, faster websites, and the best user experiences.
url: "https://danklammer.com"
production_url: https://danklammer.com
contact_email: mailman@danklammer.com
google_analytics: UA-3896262-8

# Splash page & drafts
show_splash: false
show_drafts: false

# Build settings
exclude: ["node_modules", "README", "README.md", bower.json", ".travis.yml", ".gitignore", ".gitattributes", ".gitmodules", "LICENSE", "CHANGELOG.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["/* ", " */"]
  endings: all
  blanklines: false

# Jekyll plugins
plugins:
  - jekyll-sitemap