# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Klammer
email: me@danklammer.com
description: Designer & Developer from Cleveland, Ohio
tagline: Passionate about creating digital products—obsessed with simplicity & experience.
url: "http://danklammer.com"
production_url: http://danklammer.com
contact_email: mailman@danklammer.com

# Splash page & drafts
splash: true
show_drafts: false

# Build settings
exclude: ["node_modules", "README", "README.md", bower.json", ".travis.yml", ".gitignore", ".gitattributes", ".gitmodules", "LICENSE", "CHANGELOG.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["/* ", " */"]
  endings: all
  blanklines: false