# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Klammer
email: me@danklammer.com
description: Designer & Developer from Cleveland, Ohio
tagline: Passionate about creating digital products—obsessed with simplicity & performance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danklammer.com" # the base hostname & protocol for your site
twitter_username: danklammer
github_username:  danklammer

# Build settings
markdown: kramdown
sass:
  style: compressed