siteTitle = "Dan Klammer"
siteDescr = "Passionate about creating digital products–obsessed with simplicity & performance."
siteAuthor = "Dan Klammer"

linkPrefix = "/"

# noProductionJavascript = "true"